import argparse
import json
import platform
import sys
import time
from pathlib import Path


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def write_json(path, data):
    Path(path).write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def quote(value):
    return json.dumps(str(value), ensure_ascii=False)


def render_yaml(config, trial_dir):
    train = config["train"]
    dataset = config["dataset"]
    generation = config["generation"]
    profile = config["lora_profile"]
    output_dir = trial_dir / "ai_toolkit_output"
    prompt_lines = "\n".join(f"          - {quote(prompt)}" for prompt in config["evaluation"]["prompts"])
    return f"""# Generated by lora_workshop/adapters/ai_toolkit_adapter.py
# Target: {config["project_cn"]}
# LoRA: {profile["id"]} {profile["name"]}

job: extension
config:
  name: {quote(config["project"] + "_" + profile["id"].lower())}
  process:
    - type: sd_trainer
      training_folder: {quote(output_dir)}
      device: cuda:0
      network:
        type: lora
        linear: {int(train["rank"])}
        linear_alpha: {int(train["alpha"])}
      save:
        dtype: {quote(train["precision"])}
        save_every: {max(100, int(train["steps"]) // 4)}
        max_step_saves_to_keep: 4
      datasets:
        - folder_path: {quote(dataset["local_root"])}
          caption_ext: txt
          resolution:
            - {int(dataset["resolution"])}
          cache_latents_to_disk: true
          caption_dropout_rate: {float(train["caption_dropout"])}
      train:
        batch_size: {int(train["batch_size"])}
        steps: {int(train["steps"])}
        gradient_accumulation_steps: {int(train["gradient_accumulation"])}
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        optimizer: {quote(train["optimizer"])}
        lr: {float(train["learning_rate"])}
        dtype: {quote(train["precision"])}
        ema_config:
          use_ema: false
      model:
        name_or_path: {quote(config["base_model"]["id"])}
        quantize: true
      sample:
        sample_every: {max(100, int(train["steps"]) // 2)}
        width: {int(generation["width"])}
        height: {int(generation["height"])}
        seed: {int(train["seed"])}
        guidance_scale: {float(generation["guidance_scale"])}
        sample_steps: {int(generation["sample_steps"])}
        neg: {quote(generation["negative_prompt"])}
        prompts:
{prompt_lines}
meta:
  project_cn: {quote(config["project_cn"])}
  lora_id: {quote(profile["id"])}
  lora_name: {quote(profile["name"])}
  trigger_token: {quote(dataset["trigger_token"])}
  dataset_core_ref: {quote(dataset["core_ref"])}
  annotation_standard: {quote(dataset["annotation_standard"])}
"""


def write_sample_grid(config, out_path):
    profile = config["lora_profile"]
    prompts = config["evaluation"]["prompts"]
    rows = "\n".join(
        f"<li><strong>Prompt {index + 1}</strong><p>{prompt}</p></li>"
        for index, prompt in enumerate(prompts)
    )
    html = f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <title>{profile["id"]} {profile["name"]}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Microsoft YaHei", Arial, sans-serif; margin: 36px; background: #f6f7f9; color: #151515; }}
    main {{ max-width: 980px; margin: 0 auto; background: #fff; border: 1px solid #e5e7eb; border-radius: 10px; padding: 28px; }}
    h1 {{ margin: 0 0 8px; font-size: 28px; }}
    .meta {{ color: #666; line-height: 1.8; }}
    li {{ margin: 16px 0; padding: 14px; background: #f8fafc; border-radius: 8px; }}
    p {{ margin: 6px 0 0; line-height: 1.7; }}
  </style>
</head>
<body>
  <main>
    <h1>{profile["id"]} {profile["name"]}</h1>
    <div class="meta">主题：{profile["theme"]} | 触发词：{profile["trigger"]} | 默认权重：{profile["default_weight"]}</div>
    <div class="meta">本页为 dry-run 样张占位，用于验证提示词、LoRA 矩阵和训练配置渲染。</div>
    <ol>{rows}</ol>
  </main>
</body>
</html>
"""
    Path(out_path).write_text(html, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    started = time.perf_counter()
    config = load_json(args.config)
    out_dir = Path(args.out)
    trainer_config_dir = out_dir / "trainer_config"
    trainer_config_dir.mkdir(parents=True, exist_ok=True)

    rendered_config_path = trainer_config_dir / "ai_toolkit_config.yaml"
    rendered_config_path.write_text(render_yaml(config, out_dir), encoding="utf-8")

    write_json(
        trainer_config_dir / "adapter_manifest.json",
        {
            "schema_version": "heritage-adapter-manifest-v1",
            "adapter": "ai_toolkit",
            "mode": "dry_run_compile_only" if args.dry_run else "real_training",
            "rendered_native_config_path": str(rendered_config_path),
        },
    )

    metrics = {
        "status": "not_trained",
        "dry_run": True,
        "style_fidelity": 0.0,
        "cultural_accuracy": 0.0,
        "product_transferability": 0.0,
        "prompt_adherence": 0.0,
        "artifact_control": 0.0,
        "cost_efficiency": 0.0,
    }
    write_json(out_dir / "metrics.json", metrics)

    elapsed = time.perf_counter() - started
    write_json(
        out_dir / "config.lock.json",
        {
            "schema_version": "heritage-config-lock-v1",
            "trainer_backend": config["train"]["backend"],
            "adapter": "ai_toolkit_adapter.py",
            "dry_run": True,
            "python": sys.version.split()[0],
            "platform": platform.platform(),
            "base_model": config["base_model"],
            "dataset": config["dataset"],
            "lora_profile": config["lora_profile"],
            "effective_train": config["train"],
            "generation": config["generation"],
            "rendered_native_config_path": str(rendered_config_path),
            "wall_clock_seconds": round(elapsed, 4),
        },
    )

    write_json(
        out_dir / "checkpoint_valid.json",
        {
            "valid": False,
            "dry_run": True,
            "load_test": "not run; dry-run only renders AI Toolkit config",
        },
    )
    write_sample_grid(config, out_dir / "sample_grid.html")
    (out_dir / "summary.md").write_text(
        "\n".join(
            [
                f"# {out_dir.name}",
                "",
                f"- LoRA: `{config['lora_profile']['id']} {config['lora_profile']['name']}`",
                f"- scene: `{config['primary_scene']}`",
                f"- base model: `{config['base_model']['id']}`",
                f"- dataset: `{config['dataset']['core_ref']}`",
                f"- rendered config: `{rendered_config_path}`",
                "",
                "This is a compile-only dry run. Real release requires authorized data, checkpoint validation, quality evaluation, and human review.",
            ]
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
